/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicas;

import io.ImageManager;
import java.awt.Image;
import static java.awt.image.BufferedImage.TYPE_INT_RGB;
import javax.swing.ImageIcon;

/**
 *
 * @author david
 */
public class P3Binarizar extends javax.swing.JFrame {
    private Image original;
    private boolean estaOriginal;
    private Image grises;
    private Image binarizada;
    private final int lblSize = 600;
    private int x1, y1;
    /**
     * Creates new form P2Binarizar
     */
    public P3Binarizar() {
        initComponents();
        setVisible(true);
        this.setTitle("Umbralizar");
        // Quitamos el texto de los labels
        this.lblImagen.setText("");
        this.lblUmbralizacion.setText("");
        // Abrimos la imagen
        this.original = ImageManager.openImage();
        calcularDimensionesLabels(this.original.getWidth(null), this.original.getHeight(null));
        // Se escala la imagen
        this.original = this.original.getScaledInstance(this.x1, this.y1, TYPE_INT_RGB);
        // Generamos la escala de grises
        this.grises = herramientas.EscalaGrises.generarImagenGrises(this.original);
        this.binarizada = herramientas.Umbralizacion.umbralizacionSimple(
            this.jSlider1.getValue(), this.grises);
        
        // La de escala de grises la mostramos en la izquierda
        this.lblImagen.setIcon(new ImageIcon(this.grises.getScaledInstance(
            this.x1, this.y1, Image.SCALE_DEFAULT)));
        this.estaOriginal = false;
        // La umbralización en la derecha
        this.lblUmbralizacion.setIcon(new ImageIcon(this.binarizada.getScaledInstance(
            this.x1, this.y1, Image.SCALE_DEFAULT)));
    }
    
     private void calcularDimensionesLabels(int x1, int y1) {
        double p;
        
        if(y1 >= x1) {
            p = (double)y1/(double)x1;
            if(y1 > lblSize) {
                y1 = lblSize;
                x1 = (int)(y1 / p);
            }
        }
        else {
           p = (double)x1/(double)y1;
           if(x1 > lblSize) {
                x1 = lblSize;
                y1 = (int)(x1 / p);
            }
        }
        
        this.x1 = x1;
        this.y1 = y1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagen = new javax.swing.JLabel();
        lblUmbralizacion = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblImagen.setText("jLabel1");
        lblImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagenMouseClicked(evt);
            }
        });

        lblUmbralizacion.setText("jLabel1");

        jSlider1.setMaximum(255);
        jSlider1.setValue(127);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(lblUmbralizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                    .addComponent(lblUmbralizacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        int umbral = this.jSlider1.getValue();
        this.binarizada = herramientas.Umbralizacion.umbralizacionSimple(
            umbral, this.grises);
        // En el título mostramos el valor de umbral
        this.setTitle("Umbral: " + String.valueOf(umbral));
        // Actualizar la imagen
        this.lblUmbralizacion.setIcon(new ImageIcon(this.binarizada));
    }//GEN-LAST:event_jSlider1StateChanged

    private void lblImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagenMouseClicked
        if(this.estaOriginal) {
            this.estaOriginal = false;
            this.lblImagen.setIcon(new ImageIcon(this.grises));
        }
        else {
            this.estaOriginal = true;
            this.lblImagen.setIcon(new ImageIcon(this.original));
        }
    }//GEN-LAST:event_lblImagenMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(P3Binarizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(P3Binarizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(P3Binarizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(P3Binarizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new P3Binarizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblUmbralizacion;
    // End of variables declaration//GEN-END:variables
}
