/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicas;

import herramientas.Traslacion;
import io.ImageManager;
import java.awt.Image;
import static java.awt.image.BufferedImage.TYPE_INT_RGB;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author david
 */
public class P4TemIluminacion extends javax.swing.JFrame {
    private Image enTamOriginal;
    private Image original;
    private Image efecto;
    private final int lblSize = 400;
    private int x1, y1;
    /**
     * Creates new form P4TemIluminacion
     */
    public P4TemIluminacion() {
        initComponents();
        this.lblOriginal.setText("");
        this.lblEfecto.setText("");
        this.setTitle("Temperatura e iluminación");
    }
    
    private void calcularDimensionesLabels(int x1, int y1) {
        double p;
        
        if(y1 >= x1) {
            p = (double)y1/(double)x1;
            if(y1 > lblSize) {
                y1 = lblSize;
                x1 = (int)(y1 / p);
            }
        }
        else {
           p = (double)x1/(double)y1;
           if(x1 > lblSize) {
                x1 = lblSize;
                y1 = (int)(x1 / p);
            }
        }
        
        this.x1 = x1;
        this.y1 = y1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOriginal = new javax.swing.JLabel();
        lblEfecto = new javax.swing.JLabel();
        sliderTemperatura = new javax.swing.JSlider();
        sliderIluminacion = new javax.swing.JSlider();
        btnGuardar = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblOriginal.setText("text");

        lblEfecto.setText("text");

        sliderTemperatura.setBackground(new java.awt.Color(0, 0, 0));
        sliderTemperatura.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        sliderTemperatura.setForeground(new java.awt.Color(0, 102, 102));
        sliderTemperatura.setMajorTickSpacing(25);
        sliderTemperatura.setMaximum(255);
        sliderTemperatura.setMinimum(-255);
        sliderTemperatura.setMinorTickSpacing(25);
        sliderTemperatura.setPaintLabels(true);
        sliderTemperatura.setPaintTicks(true);
        sliderTemperatura.setValue(0);
        sliderTemperatura.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderTemperaturaStateChanged(evt);
            }
        });

        sliderIluminacion.setForeground(new java.awt.Color(0, 102, 102));
        sliderIluminacion.setMajorTickSpacing(25);
        sliderIluminacion.setMaximum(255);
        sliderIluminacion.setMinimum(-255);
        sliderIluminacion.setMinorTickSpacing(25);
        sliderIluminacion.setPaintLabels(true);
        sliderIluminacion.setPaintTicks(true);
        sliderIluminacion.setValue(0);
        sliderIluminacion.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderIluminacionStateChanged(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnAbrir.setText("Abrir nueva");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });

        jLabel1.setText("Temperatura");

        jLabel2.setText("Iluminación");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                                .addComponent(lblEfecto, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sliderTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sliderIluminacion, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAbrir, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEfecto, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar)
                    .addComponent(sliderTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sliderIluminacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAbrir))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        // Abrimos la imagen
        this.enTamOriginal = ImageManager.openImage();
        calcularDimensionesLabels(this.enTamOriginal.getWidth(null), 
            this.enTamOriginal.getHeight(null));
        // Se escala la imagen
        this.original = this.enTamOriginal.getScaledInstance(this.x1, this.y1, TYPE_INT_RGB);
        this.efecto = this.original.getScaledInstance(this.x1, this.y1, TYPE_INT_RGB);
        // La original la mostramos en la izquierda
        this.lblOriginal.setIcon(new ImageIcon(this.original.getScaledInstance(
            this.x1, this.y1, Image.SCALE_DEFAULT)));
        
        // A la que se aplica el efecto a la derecha
        this.lblEfecto.setIcon(new ImageIcon(this.efecto.getScaledInstance(
            this.x1, this.y1, Image.SCALE_DEFAULT)));
        // Los slider los regresamos a 0
        this.sliderTemperatura.setValue(0);
        this.sliderIluminacion.setValue(0);
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void sliderTemperaturaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderTemperaturaStateChanged
        // La temperatura
        this.efecto = Traslacion.cambiarTemperatura(this.original, 
            this.sliderTemperatura.getValue());
        // La iluminación
        this.efecto = Traslacion.cambiarIluminacion(this.efecto, 
            this.sliderIluminacion.getValue());
        // Actualizamos en la pantalla
        this.lblEfecto.setIcon(new ImageIcon(this.efecto.getScaledInstance(
            this.x1, this.y1, Image.SCALE_DEFAULT)));
    }//GEN-LAST:event_sliderTemperaturaStateChanged

    private void sliderIluminacionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderIluminacionStateChanged
        // La iluminación
        this.efecto = Traslacion.cambiarIluminacion(this.original, 
            this.sliderIluminacion.getValue());
        // La temperatura
        this.efecto = Traslacion.cambiarTemperatura(this.efecto, 
            this.sliderTemperatura.getValue());
        // Actualizamos en la pantalla
        this.lblEfecto.setIcon(new ImageIcon(this.efecto.getScaledInstance(
            this.x1, this.y1, Image.SCALE_DEFAULT)));
    }//GEN-LAST:event_sliderIluminacionStateChanged

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // Guardar la imagen con el efecto
        if(this.efecto != null) {
            JFileChooser f = new JFileChooser();
            f.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY); 
            f.showSaveDialog(null);
            // Aplicamos la temperatura
            Image res = Traslacion.cambiarTemperatura(this.enTamOriginal, 
                this.sliderTemperatura.getValue());
            // La iluminación
            res = Traslacion.cambiarIluminacion(res, this.sliderIluminacion.getValue());
            //System.out.println(f.getSelectedFile());
            String path = f.getSelectedFile().getAbsolutePath();
            try {
                if(ImageManager.saveImage(path, res, "png"));
            }
            catch (IOException ex) {
                ex.printStackTrace();
            }
        }
        else System.out.println("Abre una imagen primero");
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(P4TemIluminacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(P4TemIluminacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(P4TemIluminacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(P4TemIluminacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new P4TemIluminacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblEfecto;
    private javax.swing.JLabel lblOriginal;
    private javax.swing.JSlider sliderIluminacion;
    private javax.swing.JSlider sliderTemperatura;
    // End of variables declaration//GEN-END:variables
}
